# Generated by Django 5.0.3 on 2024-04-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='requires_shipping',
            new_name='requires_delivery',
        ),
    ]
