# Generated by Django 5.0.3 on 2024-05-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_requires_shipping_order_requires_delivery'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orderitem',
            managers=[
            ],
        ),
    ]
